// Generated by LiveScript 1.2.0
var deferSrcSetters, show;
deferSrcSetters = [];
angular.element(document).ready(function(){
  var i$, ref$, len$, func, results$ = [];
  for (i$ = 0, len$ = (ref$ = deferSrcSetters).length; i$ < len$; ++i$) {
    func = ref$[i$];
    results$.push(func());
  }
  return results$;
});
angular.module("kde.linux.org.tw", ['firebase']).factory({
  fireRoot: ['angularFireCollection'].concat(function(angularFireCollection){
    var url;
    url = "https://kde-tw.firebaseio.com";
    return new Firebase(url);
  })
}).directive('deferSrc', function(){
  return {
    restrict: 'A',
    link: function(scope, iElement, iAttrs, controller){
      var src;
      src = iElement.attr('defer-src');
      return deferSrcSetters.push(function(){
        return iElement.attr('src', src);
      });
    }
  };
}).controller({
  EventCtrl: ['$scope', 'angularFireCollection', 'fireRoot'].concat(function($scope, angularFireCollection, fireRoot){
  	return null;
  })
}).controller({
  BlogCtrl: ['$scope', 'angularFireCollection', 'fireRoot'].concat(function($scope, angularFireCollection, fireRoot){
    return $scope.articles = angularFireCollection(fireRoot.child("feed/blog/articles").limit(10));
  })
}).controller({
  FeaturedCtrl: ['$scope', 'angularFireCollection'].concat(function($scope, angularFireCollection){
  	return null;
  })
});
show = function(){
  var prjImg, h;
  prjImg = $('#prj-img');
  prjImg.animate({
    opacity: 1
  }, 500);
  h = [40 + prjImg.height()][0];
  return $('#prj-img-div').animate({
    height: h + "px"
  }, 500);
};
